### ISSUE TITLE
Arquivos javascript não mais necessários

### ISSUE THREAD

**Issue by LeoFuso** [LeoFuso/compilador-minivisualg#14]
Posso removê-los, Gabriel?

Entendo que, para fins de progresso no desenvolvimento do projeto, eles foram extremamente úteis, mas sinto que não são mais pertinentes, apenas em casos de mudanças futuras na gramática.

Dito isso, talvez fosse interessante realizar a conversão desses códigos para C. Não acha?

A geração de tabela de parseamento em C pode ser muito divertido =)

@gmfc

**Comment by gmfc** [comment]
Boa idéia.
Verei o que posso fazer.
